package com.example.jubinandchildren

// 뷰 페이저에 들어갈 아이템
fun getReviewList(): ArrayList<ReviewList> {
    return arrayListOf(
        ReviewList("choco", R.drawable.game_cover_palworld, "이화민","팰월드","잘 섞은 비빔밥의 표본, 포켓몬과 팰이 매우 유사하지만 포켓몬에는 없는 다양한 컨텐츠로 실시간 접속 유저 210만을 달성한 게임입니다. 이 게임에서는 하면서 느낀 바로 포켓몬과 같다고 여겨지는 팰과 플레이어간의 상하관계가 확실하고 잡을 수 있는게 팰 뿐만이 아닌 사람도 잡을 수 있다는점과 총기와 같은 무기를 사용도 가능하다는 점에서 리얼리티가 있다고 생각되었습니다","#오픈월드 #TPS #샌드박스 #서바이벌","액션",10000,4.5f, R.drawable.palworld_screenshot_1, R.drawable.palworld_screenshot_2, R.drawable.palworld_screenshot_3, R.drawable.palworld_screenshot_4, R.drawable.palworld_screenshot_5, R.drawable.palworld_screenshot_6),
        ReviewList("choco", R.drawable.game_cover_factorio, "이화민","팩토리오","외계 행성에 불시착해서 탈출하기 위한 시뮬레이션 게임입니다. 제가 해본 게임중 최고의 시간삭제 게임으로 코딩을 좋아하시는 모두에게 추천드리고 싶습니다! 게임을 시작하게 되면 여러 종류의 자원을 구해 시설을 발전시키게 되며 최종적으로 로켓을 만들어 탈출해야합니다. 위 과정에서 자원으로 부품과 기계를 만드는 과정이 있는데 만들고나면 더 좋은 최적화 방법이 계속 생각나 끊임없이 생각하면서도 시간이 빨리가는 게임이였습니다","#샌드박스 #건설_경영_시뮬레이션 #타워_디펜스 #할인_절대로_안함","시뮬레이션",40000,4.0f, R.drawable.factorio_screenshot_6, R.drawable.factorio_screenshot_1, R.drawable.factorio_screenshot_2, R.drawable.factorio_screenshot_3, R.drawable.factorio_screenshot_4, R.drawable.factorio_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_core_keeper, "이화민","코어키퍼","땅 속으로 떨어져 그곳을 탐험하며 다양한 생물과 조우하고 새로운 장비를 구할 수 있고 스킬을 강화해서 다양한 방법으로 성장이 가능합니다. 그래픽만 보면 스타듀밸리와 비슷하다고 볼 수 있지만 RPG 요소가 크고 자동화 요소가 많아 시간가는줄 모르고 계속하게 되었던 게입입니다","#샌드박스 #어드벤처 #할인때만_구매추천","어드벤처",17500,4.5f, R.drawable.corekeeper_screenshot_6, R.drawable.corekeeper_screenshot_1, R.drawable.corekeeper_screenshot_2, R.drawable.corekeeper_screenshot_3, R.drawable.corekeeper_screenshot_4, R.drawable.corekeeper_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_apex_legend, "이화민","에이펙스 레전드","이 게임의 장점이자 단점은 재미만 있는 게임인것 같습니다. 배틀그라운드와 같은 배틀로얄이지만 개인적인 생각으로는 배틀그라운드가 가진 단점을 개선해낸 게임이라 느껴집니다. 속도감이 엄청 빠르고 장거리 이동에 탈것을 의존하지 않으며 배틀 로얄에 항상 있는 생존만을 위한 플레이를 배제하고 싸움을 권장하는 플레이 방식이 제 취향에 잘 맞았던것 같습니다 단점이라고 하면 깊게 즐길수록 나타나는 서버간의 핑차이 일본서버와 대만서버에서 플레이를 해야하는 환경때문에 핑차이로 인한 불쾌감이 발생해 안타까운것 같습니다.","#FPS #배틀로얄 #히어로_슈팅_게임 #무료게임","슈팅",0,5.0f, R.drawable.apex_legend_screenshot_6, R.drawable.apex_legend_screenshot_1, R.drawable.apex_legend_screenshot_2, R.drawable.apex_legend_screenshot_3, R.drawable.apex_legend_screenshot_4, R.drawable.apex_legend_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_apex_legend, "이화민","에이펙스 레전드","이 게임의 장점이자 단점은 재미만 있는 게임인것 같습니다. 배틀그라운드와 같은 배틀로얄이지만 개인적인 생각으로는 배틀그라운드가 가진 단점을 개선해낸 게임이라 느껴집니다. 속도감이 엄청 빠르고 장거리 이동에 탈것을 의존하지 않으며 배틀 로얄에 항상 있는 생존만을 위한 플레이를 배제하고 싸움을 권장하는 플레이 방식이 제 취향에 잘 맞았던것 같습니다 단점이라고 하면 깊게 즐길수록 나타나는 서버간의 핑차이 일본서버와 대만서버에서 플레이를 해야하는 환경때문에 핑차이로 인한 불쾌감이 발생해 안타까운것 같습니다.","#FPS #배틀로얄 #히어로_슈팅_게임 #무료게임","슈팅",0,5.0f, R.drawable.apex_legend_screenshot_6, R.drawable.apex_legend_screenshot_1, R.drawable.apex_legend_screenshot_2, R.drawable.apex_legend_screenshot_3, R.drawable.apex_legend_screenshot_4, R.drawable.apex_legend_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_apex_legend, "이화민","에이펙스 레전드","이 게임의 장점이자 단점은 재미만 있는 게임인것 같습니다. 배틀그라운드와 같은 배틀로얄이지만 개인적인 생각으로는 배틀그라운드가 가진 단점을 개선해낸 게임이라 느껴집니다. 속도감이 엄청 빠르고 장거리 이동에 탈것을 의존하지 않으며 배틀 로얄에 항상 있는 생존만을 위한 플레이를 배제하고 싸움을 권장하는 플레이 방식이 제 취향에 잘 맞았던것 같습니다 단점이라고 하면 깊게 즐길수록 나타나는 서버간의 핑차이 일본서버와 대만서버에서 플레이를 해야하는 환경때문에 핑차이로 인한 불쾌감이 발생해 안타까운것 같습니다.","#FPS #배틀로얄 #히어로_슈팅_게임 #무료게임","슈팅",0,5.0f, R.drawable.apex_legend_screenshot_6, R.drawable.apex_legend_screenshot_1, R.drawable.apex_legend_screenshot_2, R.drawable.apex_legend_screenshot_3, R.drawable.apex_legend_screenshot_4, R.drawable.apex_legend_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_apex_legend, "이화민","에이펙스 레전드","이 게임의 장점이자 단점은 재미만 있는 게임인것 같습니다. 배틀그라운드와 같은 배틀로얄이지만 개인적인 생각으로는 배틀그라운드가 가진 단점을 개선해낸 게임이라 느껴집니다. 속도감이 엄청 빠르고 장거리 이동에 탈것을 의존하지 않으며 배틀 로얄에 항상 있는 생존만을 위한 플레이를 배제하고 싸움을 권장하는 플레이 방식이 제 취향에 잘 맞았던것 같습니다 단점이라고 하면 깊게 즐길수록 나타나는 서버간의 핑차이 일본서버와 대만서버에서 플레이를 해야하는 환경때문에 핑차이로 인한 불쾌감이 발생해 안타까운것 같습니다.","#FPS #배틀로얄 #히어로_슈팅_게임 #무료게임","슈팅",0,5.0f, R.drawable.apex_legend_screenshot_6, R.drawable.apex_legend_screenshot_1, R.drawable.apex_legend_screenshot_2, R.drawable.apex_legend_screenshot_3, R.drawable.apex_legend_screenshot_4, R.drawable.apex_legend_screenshot_5),
        ReviewList("choco", R.drawable.game_cover_ghost_recon, "이화민","고스트 리콘","고스트 리콘은 이전작부터 비교적 최근에 나온 작품이 있으나 2015년도에 출시한 Wildlands 시리즈를 기준으로 리뷰를 작성하겠습니다. 고스트 리콘은 플레이 방식이 다양합니다. 저격총이나 권총 등 무기로 잠입 플레이를 하는 방식도 있고 발각 되었을때 혹은 잠입 플레이가 아닌 다른 플레이를 하고싶을때 지형지물을 이용하거나 해서 전면전을 하는 방식도 가능합니다. 여러 지역을 돌아다니며 총기와 부품등을 찾고 임무나 필드파밍을 통해 얻은 재화로 스킬을 강화하며 강해질 수 있는 요소도 있고 마약상을 전부 처리하는 스토리까지 즐길 요소가 많은 게임이기에 추천드리고 싶습니다. 단점으로는 게임의 완성도 부분중 탈것을 탈때의 시점정리로 인한 멀미감, 오픈월드에서 점프가 없음으로 생기는 답답함,  그 외 가까운 위치에 있는 아이템의 위치표시 등이 있었습니다.","#FPS #택티컬_슈터 #할인때만_구매추천","슈팅",55000,3.5f, R.drawable.ghost_recon_screenshot_6, R.drawable.ghost_recon_screenshot_1, R.drawable.ghost_recon_screenshot_2, R.drawable.ghost_recon_screenshot_3, R.drawable.ghost_recon_screenshot_4, R.drawable.ghost_recon_screenshot_5),
        ReviewList("orinugoori9", R.drawable.game_cover_planet_zoo, "김현지","플래닛 주","동물원 주인이 되어서 관리하는 게임입니다. 어릴 때 주타이쿤 하던게 생각나면서 갑자기 하고싶어서 세일도 안할 때 사버렸는데, 정가주고사기엔 너무 비싸다고 생각해요. 그리고 하다보면 점점 진짜 내가 게임을 하는건지 경영을 하는건지 스트레스를 받을 수도 있습니다. 멍청한 사육사들이 본인 숙소를 알아서 찾아가지못하고 일을 알잘딱으로 못해서 하나하나 지정해주어야하는게 매우 열받기 때문입니다.","#시뮬레이션 #경영 #건설 #동물","경영",46000,3.0f, R.drawable.planet_zoo_screenshot_6, R.drawable.planet_zoo_screenshot_1, R.drawable.planet_zoo_screenshot_2, R.drawable.planet_zoo_screenshot_3, R.drawable.planet_zoo_screenshot_4, R.drawable.planet_zoo_screenshot_5),
        ReviewList("orinugoori9", R.drawable.game_cover_supper_bunny_man, "김현지","슈퍼 버니 맨","깜찍하고 흐물흐물한 토끼로 길을 가는 게임입니다. 몸을 마음대로 가눌 수 없기 때문에 친구랑 같이하면 꽤나 웃겨요 혼자서 하는거보다 친구랑 같이 해보시길 추천 드립니당 근데 세일할 때 사세요.","#액션 #인디 #토끼 #친구랑","인디",15250,3.5f, R.drawable.superbunnyman_screenshot_6, R.drawable.superbunnyman_screenshot_1, R.drawable.superbunnyman_screenshot_2, R.drawable.superbunnyman_screenshot_3, R.drawable.superbunnyman_screenshot_4, R.drawable.superbunnyman_screenshot_5),
        ReviewList("orinugoori9", R.drawable.game_cover_hogwarts_legacy, "김현지","폴리 브릿지","조건에 맞는 다리를 주어진 예산 내로 만드는 게임입니다. 페이커가 하는거 보고 나중에 해봐야지하다가 90%세일하길래 구매했습니다. 1000원 내외로 구매한 거 치고는 아주 좋다고 생각합니다 가성비 최고입니다. 은근 시간이 살살 녹아욤. 근데 저는 멍청이라서 하나깨는데 오래 걸려요","#시뮬레이션 #인디","시뮬레이션",10500,4.0f, R.drawable.polybridge_screenshot_6, R.drawable.polybridge_screenshot_1, R.drawable.polybridge_screenshot_2, R.drawable.polybridge_screenshot_3, R.drawable.polybridge_screenshot_4, R.drawable.polybridge_screenshot_5),
        ReviewList("apape", R.drawable.game_cover_cyberpunk_2077, "공명선","사이버펑크","패치가 거듭될수록 재밌어지는 액션 오픈월드 갓겜. 애니메이션 보고 DLC까지 해야 재밌다","#오픈월드 #RPG #FPS","",66000,3.8f, R.drawable.cybepunk_screenshot_6, R.drawable.cybepunk_screenshot_1, R.drawable.cybepunk_screenshot_2, R.drawable.cybepunk_screenshot_3, R.drawable.cybepunk_screenshot_4, R.drawable.cybepunk_screenshot_5),
        ReviewList("apape",R.drawable.game_cover_zelda, "공명선","젤다의 전설","메타크리틱 점수 97점, 2017년 최다 GOTY. 안 해본 사람은 있어도 중간에 그만둔 사람은 없다","#오픈월드 #어드벤처 #샌드박스","",74800,5.0f, R.drawable.zelda_screenshot_6, R.drawable.zelda_screenshot_1, R.drawable.zelda_screenshot_2, R.drawable.zelda_screenshot_3, R.drawable.zelda_screenshot_4, R.drawable.zelda_screenshot_5),
        ReviewList("apape",R.drawable.game_cover_gta_5, "공명선","GTA 5","누구나 한번쯤은 들어본 게임. GTA 6 출시 전에 찍먹 한 번","#오픈월드 #TPS #액션","",44000,4.4f, R.drawable.gta_screenshot_6, R.drawable.gta_screenshot_1, R.drawable.gta_screenshot_2, R.drawable.gta_screenshot_3, R.drawable.gta_screenshot_4, R.drawable.gta_screenshot_5),
        ReviewList("apape",R.drawable.game_cover_human_fall_flat, "공명선","휴먼 폴 플랫","친구들이랑 해도 재밌고, 혼자 해도 재밌는, 정신없는 플랫폼 퍼즐 게임.","#퍼즐 #플랫폼"," ",20500,3.5f, R.drawable.humanfallflat_screenshot_6, R.drawable.humanfallflat_screenshot_1, R.drawable.humanfallflat_screenshot_2, R.drawable.humanfallflat_screenshot_3, R.drawable.humanfallflat_screenshot_4, R.drawable.humanfallflat_screenshot_5),
        ReviewList("mwamwa",R.drawable.game_cover_project_zomboid, "황주빈","프로젝트 좀보이드","윤회에 익숙해져 아포칼립스 생존 성공하자! 초반에 아무것도 모를 때만 어려움 나머지는 할 만 합니다. ","#오픈월드 #시뮬레이션 #인디 #RPG ","",21500,4.5f, R.drawable.zomboid_screenshot_6, R.drawable.zomboid_screenshot_1, R.drawable.zomboid_screenshot_2, R.drawable.zomboid_screenshot_3, R.drawable.zomboid_screenshot_4, R.drawable.zomboid_screenshot_5),
        ReviewList("mwamwa",R.drawable.game_cover_rimworld, "황주빈","림월드","700시간 녹였습니다 아직 2회차밖에 못해봤어요. 정착지 꾸리기 좋아하십니까? 림월드 하십시오. 뒷 목 잡는 이야기를 원하십니까? 림월드 하십시오","#인디 #시뮬레이션 #전","",37500,5.0f, R.drawable.rimworld_screenshot_6, R.drawable.rimworld_screenshot_1, R.drawable.rimworld_screenshot_2, R.drawable.rimworld_screenshot_3, R.drawable.rimworld_screenshot_4, R.drawable.rimworld_screenshot_5),
        ReviewList("mwamwa",R.drawable.game_cover_slime_rancher, "황주빈","슬라임 랜처","귀여움이 다 하는 게임,  생각보다 루즈하지 않고 있을 챙길 재미는 다 챙겼다. 미니게임도 재밌어요.","#어드벤쳐 #인디 # 시뮬레이션","",21500,4.0f, R.drawable.slime_screenshot_6, R.drawable.slime_screenshot_1, R.drawable.slime_screenshot_2, R.drawable.slime_screenshot_3, R.drawable.slime_screenshot_4, R.drawable.slime_screenshot_5),
        ReviewList("mwamwa",R.drawable.game_cover_stardew_valley, "황주빈","스타듀 밸리","폭닥한 연애 시뮬레이션 농사 게임 좋아하면 좋아요. 최근에 업데이트 하면서 컨텐츠 더 풍성해짐","#인디 # RP #시뮬레이","",16000,4.5f, R.drawable.stardewvalley_screenshot_5, R.drawable.stardewvalley_screenshot_1, R.drawable.stardewvalley_screenshot_2, R.drawable.stardewvalley_screenshot_3, R.drawable.stardewvalley_screenshot_4, R.drawable.stardewvalley_screenshot_1),
        ReviewList("mwamwa",R.drawable.game_cover_dont_starve_together, "황주빈","돈 스타브 투게더","게임 자체는 어렵다고 소문이 자자하지만 계속해서 유저들 편의나 난이도 패치 해주고 그거에 더해서 추가 컨텐츠들을 쭉쭉 내줘요. 모드 지원도 편해서 난이도를 낮춰도 게임이 어려운 사람들에게 다양한 맛을 볼 수 있게 해주는 게임입니다","#어드벤쳐 #인디 #RPG #시뮬레이션","",5270,4.5f, R.drawable.dontstarve_screenshot_6, R.drawable.dontstarve_screenshot_1, R.drawable.dontstarve_screenshot_2, R.drawable.dontstarve_screenshot_3, R.drawable.dontstarve_screenshot_4, R.drawable.dontstarve_screenshot_5),
        ReviewList("ruruha545",R.drawable.img_minecraft_main, "박정호", "마인크래프트","전 세계 3억장 판매, 더 이상 말이 필요없는 세계 최고의 게임. 어린이부터 어른까지, 블록 쌓기부터 작곡까지, 모든 장르를 하나의 플랫폼으로 즐길 수 있습니다. 지금바로 나만의 세계를 만들어보세요.","#서바이벌 #샌드박스", "샌드박스",30000,5.0f, R.drawable.mine06, R.drawable.mine01, R.drawable.mine02, R.drawable.mine03, R.drawable.mine04, R.drawable.mine05),
        ReviewList("ruruha545",R.drawable.img_wows_main, "박정호", "월드오브워쉽","대체제가 없는 세계 최고의 2차대전기 해전 PVP 게임. 글로벌 론칭 9주년-상시 5천명 동시접속 유지-다양한 콜라보레이션 컨텐츠(트랜스포머, 벽람항로 등). 유능한 함장으로써, 아군을 승리로 이끌어주세요.","#슈팅 #온라인 #PVP #MMORPG", "슈팅",0,4.0f, R.drawable.wows06, R.drawable.wows01, R.drawable.wows02, R.drawable.wows03, R.drawable.wows04, R.drawable.wows05),
        ReviewList("ruruha545",R.drawable.img_aoe2_main, "박정호", "에이지오브엠파이어2","세월이 지나도 이어지는 그 이름, 에이지오브엠파이어. 중세를 배경으로 펼쳐지는 시리즈 최고의 히트작, 게르만족의 대이동부터 콘스탄티노플의 함락까지, 지금 그 역사의 현장으로 여러분을 초대합니다.","#전략시뮬레이션 #온라인", "전략시뮬레이션",21000,4.0f, R.drawable.aoe06, R.drawable.aoe01, R.drawable.aoe02, R.drawable.aoe03, R.drawable.aoe04, R.drawable.aoe05),
    )
}